version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: recetas_postgres
    restart: always
    environment:
      POSTGRES_USER: usuario_receta
      POSTGRES_PASSWORD: password_segura
      POSTGRES_DB: recetas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: